keys:
  - &jade age1x2t55uu60pkjsmggep284a4pvx05w7jyrxdnd503k26vp8ecnf2qk8zede
  - &ruby age1vpwvdgz268pqt7m3xk0w6vu5z5j27quwn4p6xnghnyncqqn2m4ks9wlqg7

creation_rules:
  - path_regex: secrets/[^/]+\.ya?ml$
    key_groups:
    - age:
      - *jade
      - *ruby

