mailserver_password: ENC[AES256_GCM,data:Smof+J8zcW+nMWm2mRv0V5kfMypR2MW19Zyq5jQ9C+aAeamqycub9sebWS/TUYZ/mUSbnG/U6BtpcylH,iv:gFfsARsTwi9GEfmfryKccoB+dRzFQgIGBoDbbkOzxSQ=,tag:HBOHu3/PrJNKOHpRJxXLUA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1laxes9xz25p0lhcflurv9mxyxm22g6ghw2d7c0hlxdkft7ettptsr7nmjw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWRk10T1l5SEVsbEJJdGZa
            T090QmR4NHB5Q1Q2UjUrUHRsYXVzUWpQeUdJCmNhT0xIZTlBNnd0QklHYkJuUmEy
            cVpxL003MUxXQ0NsMllsUHhkVFljcjgKLS0tIGdtN3VJOG1aTkRsdkZNbGdxTGV3
            UnhLaEh2c0lJazZZUnk3VlZQVUVoNEkK7C23mVa8mDNanJbcVEoH3g74wU6j78Dr
            92rn+IqlotpQGPGaVP3DIOSwYB7CwZUQH4pa4p6PsBZkFzs/FAe+vw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1vpwvdgz268pqt7m3xk0w6vu5z5j27quwn4p6xnghnyncqqn2m4ks9wlqg7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsL3pyL2Q4OWpQQitVZE9F
            cjJ1bC9seTNzRSt1bjZHdE15Rm1oOGhoQkhjCjhyMkVaWnZyUHFONW1pdUJWQmhm
            cU9QdkFnQnAvRVZKSmdDcEg4ZXFCRE0KLS0tIEViSWhmYlZmQjkrWWt5bzNMc1lv
            SFVrdGsrYWpNaUJPYjlYS01PY09GQjgKXhHAlYggRHv/aGqi63i9VoNDLtEQzGTB
            XXXAGfUKjbKBXCQyCoqyrZy9UUBGFa1KYO8w0NRUvDKt0HaiU1tV3A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1lxmhrxyqjev4vznfsmve6fumlpqnudlyyur3wu6tymgj9gns7qlsnyv7wj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnQ2FsS3dOOFp2c0RWRitY
            MzNLd2JVNWVPenVlaVFZcFNyYWtUVURIRTBzCkZwVmVrQ1FhY2d6aTRCcSs5aVhD
            aCtmNUYrRVBidzE0bWtMVFUwNC95bTAKLS0tIFI3eFNZQ3dGTHkwY2NZaTluOE5u
            U3YzVnhyZit2ZFBYSmJrNy9BYkRkbncKfDrbYG1kcER1PnJGkZwxtYjbUiKSlPBj
            uFQPQcDn5Hoh6nGx/uwc1InmoqZipaeeNI/2iGBLGCqha+ZnANZohw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-16T21:55:15Z"
    mac: ENC[AES256_GCM,data:n3L3yiwSqM0KoN+FwsyqkiU13FkP+GdM8yHU9iY2++Xv3N0OOZgWkyHN587hgWq7xOFOfqZM26sG1V2TDCbyc4KlcouSd76hCmwpAacOu3t6EelmiK0XI+qh7yJkbfZoso9ctM4/EVyhFkM6xcBppYHaSXdN/7mFb7ZQGn3rhd4=,iv:1rJxh/C+D6VQut8ZE0YkpokfCH9RtYlFrbhJ4dZzKdI=,tag:hWVzNzQemZFvf/l0LrYZ8w==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
