mailserver_password: ENC[AES256_GCM,data:ZN3QBVA6kRUV+jmg3RyBLKc=,iv:f7XT2dK02NYvSxa9LgtV6VRs2jVDOOxhQTgISGzc8oc=,tag:DYTHXS9pi5gjUc61p0LmAQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1x2t55uu60pkjsmggep284a4pvx05w7jyrxdnd503k26vp8ecnf2qk8zede
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5Tk5NWHZXYWVnbERvRHN5
            NEZ3eit3VXc1WXNNQ24yT250Yml2RUtkSUE0CitWWWVnSzA4UDNSWW1EK0x4UVFQ
            UzV0VGVnM3R0MEcvN3dvNHM3SW9Gb1kKLS0tIEFJNEtyY251RnFuNitVOTN2QXV3
            MHdHNHVPRHdaT1lwaDlQK1dRKzlmVG8KO1/wy9yzs700hFztYfYxz0AEmgNOh47X
            tEbbiBLyJkiWrwGdtT7X3ZnfIH1yq8r2GMbKmAg9yyvifgBQuhroMw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1vpwvdgz268pqt7m3xk0w6vu5z5j27quwn4p6xnghnyncqqn2m4ks9wlqg7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFa1NrbW8rV3diK1RWYkth
            eVdLVGdSU3dmck9lbzFwdExwcDhWTHMwbkRZCmNKc1J3VERNMDEyREJEbzQrVHZm
            bXdGRWFQdHNGUXh2Nk1jOUJmVlc0ajQKLS0tIHpHYjRZV0hLdlk3TXJEdzhrd1JD
            WG13dmc3OHU3Y0FuZHZSZ1NiWGZUNkkK2YZxvp9hnxlyLJVHNp/c8fAKbq1jQdyM
            SIphl5dwKRqRAPC1ZL2h0UwP2Xn4BWZitqeMi+u7LO26+M2843U0Cg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-16T21:40:40Z"
    mac: ENC[AES256_GCM,data:A8viLi1Fte2YQxxaGRLhmTmJlWb1edq67dA4l+/J0bFCjy933NBbjj2/Dl+iwxbOynFUpFLzoaXeaUkJUnvhU31cfp/ruqKrlsC0UuFelaAkWEf+hJi5+biGidfc1cA15hu1BH2gbPRih2rTQRYSklgOG2j+VvZfu/cAz4/oAcE=,iv:sj0f/zRSv3webC8y/S/Yn5UEEHy7vOL2tYSAoqP9QK0=,tag:l6QZQczpNEr+e57zl8TKhA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
