#ENC[AES256_GCM,data:nBlMHuFYyg==,iv:pfSU/oaqEeWh1M71TyDX5ms8ZQKDJpK62CC/WOi5AP4=,tag:Nt3iss2TCniI3ijXhiwWfA==,type:comment]
defaultPassword: ENC[AES256_GCM,data:0g+zVcPO,iv:ogGnExBiQ8k6qWvFoaRuDc8fHl9eagxEkiCGy+gBBoo=,tag:sSXiIcfNX1clfyy5XlBcww==,type:int]
#ENC[AES256_GCM,data:PC8gGG6U5Fyt,iv:+k0lYtbXRMO5pzDodHQ8bpx2B6gqsqnrgpOfrggk9AU=,tag:gxlut2uH4LWoCss1J7lhJQ==,type:comment]
spotify:
    password: ENC[AES256_GCM,data:LS2nxbI//az2IFL+5Kh6H08=,iv:IsZxZAxXZFEHTPD0z3y284q9kXrhi6c0p1YzfY5dXIU=,tag:6duiQ8VrFK4yjs304l+Lpg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1x2t55uu60pkjsmggep284a4pvx05w7jyrxdnd503k26vp8ecnf2qk8zede
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5SzU4UWd1OEJtZC9QdDlj
            Slg0QjBBc3IwMTVCdDhpTk9Ib2l2WEpmb0NFCnM0YTZlQTY2YWc3WFdQWVhSNWhO
            ajNVSm5XMVEwWTF3NTd6SUFGVkw2NU0KLS0tIFNjUXQvMnBleGNNWklBOEtSZk1U
            MlF0djk1WlRkTUpjVUhlTVFNQXh5eTQKd20GqffX1FnKilf6/fL86rG4e1UcEHLN
            LgD4cdlh9zaGinNuc9vH03zUBHKAFTIRJMPZM7cGwPYrBesTzir+wg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1vpwvdgz268pqt7m3xk0w6vu5z5j27quwn4p6xnghnyncqqn2m4ks9wlqg7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjYUJCMzg2NXpIcGlEMFJU
            aDhGUE5uQXR4a1V5UEcvcWZudmltQnVSeDNnCmo5RWhsTUFWa215c3J4Mnl2dWM2
            cXFEenRNcXBaRUdQSVl1WHhpdXNMUDgKLS0tIFExL1VkczhCMDNsbDljMWFMckJz
            Wjg3Q3l6T2tQQ2JUSmFPb1pMaTV0cVkK6mOshb3M345gpbZwwsdnxyeEhJiJX+WJ
            qbjbR88HhQyai5TLLL/QWnhkOKkpsdW3plnITIrvFeRPclCEKhQaaA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-01-05T09:49:43Z"
    mac: ENC[AES256_GCM,data:3QpmLu7OKQBQRmYEgMhBr57Wlc3wukz0WWuQaZP49zip8QxQe1aPk+pRfgVHNPS1JD6sYZ4yL+BqCwd9rEVWhpo+io9xLlmPFgLOXTFRZN5KXKgsB2b/i4l8tQj0Wa5xFEwasIgAsqI82xVnDaE3+RUZ14OAYEom5OK5fl+bjN8=,iv:zCIxMiyRM7cKTshCQU+HCULlKQtd6n/iJrISY4hFBIA=,tag:V0cqTevPB5v+SF5E1Qq9MA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
