github-user-email: ENC[AES256_GCM,data:hb32wSoJBHlR2QOMZgUd0rGf//ENc0P0XwcfMjsII7d8Lw4JRrdm0Ev4G7SvWeo=,iv:QKeJzFSpxtfh7O88C8pW5HKTc9gJY1yAwLivJM0LmRU=,tag:Fd3WDUkBR4XrLAA0t7d0hw==,type:str]
github-user-name: ENC[AES256_GCM,data:uw==,iv:sDvfMFTEAMGC4asywUYMPVGXgOT4EowlOHCkwfIePTE=,tag:NNX8nsaUpz2ID4D8WapzOg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1laxes9xz25p0lhcflurv9mxyxm22g6ghw2d7c0hlxdkft7ettptsr7nmjw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWRk10T1l5SEVsbEJJdGZa
            T090QmR4NHB5Q1Q2UjUrUHRsYXVzUWpQeUdJCmNhT0xIZTlBNnd0QklHYkJuUmEy
            cVpxL003MUxXQ0NsMllsUHhkVFljcjgKLS0tIGdtN3VJOG1aTkRsdkZNbGdxTGV3
            UnhLaEh2c0lJazZZUnk3VlZQVUVoNEkK7C23mVa8mDNanJbcVEoH3g74wU6j78Dr
            92rn+IqlotpQGPGaVP3DIOSwYB7CwZUQH4pa4p6PsBZkFzs/FAe+vw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1vpwvdgz268pqt7m3xk0w6vu5z5j27quwn4p6xnghnyncqqn2m4ks9wlqg7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsL3pyL2Q4OWpQQitVZE9F
            cjJ1bC9seTNzRSt1bjZHdE15Rm1oOGhoQkhjCjhyMkVaWnZyUHFONW1pdUJWQmhm
            cU9QdkFnQnAvRVZKSmdDcEg4ZXFCRE0KLS0tIEViSWhmYlZmQjkrWWt5bzNMc1lv
            SFVrdGsrYWpNaUJPYjlYS01PY09GQjgKXhHAlYggRHv/aGqi63i9VoNDLtEQzGTB
            XXXAGfUKjbKBXCQyCoqyrZy9UUBGFa1KYO8w0NRUvDKt0HaiU1tV3A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1lxmhrxyqjev4vznfsmve6fumlpqnudlyyur3wu6tymgj9gns7qlsnyv7wj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnQ2FsS3dOOFp2c0RWRitY
            MzNLd2JVNWVPenVlaVFZcFNyYWtUVURIRTBzCkZwVmVrQ1FhY2d6aTRCcSs5aVhD
            aCtmNUYrRVBidzE0bWtMVFUwNC95bTAKLS0tIFI3eFNZQ3dGTHkwY2NZaTluOE5u
            U3YzVnhyZit2ZFBYSmJrNy9BYkRkbncKfDrbYG1kcER1PnJGkZwxtYjbUiKSlPBj
            uFQPQcDn5Hoh6nGx/uwc1InmoqZipaeeNI/2iGBLGCqha+ZnANZohw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-03-01T11:41:15Z"
    mac: ENC[AES256_GCM,data:OCLdtpNV4ZPRpLeBK8ZzlBHXQfAPgmN4J96ukMGQDhli1BjZtR1ISEDHwMK8GVXToRm4vPx8NhJjSpyv92PxXcIhHoIB87991uxsXFCfo5vHDdk9Hiu6XaaJ8nG6uEFw/7ozJz8gf8r4kCfn/wLjsGPLLYpHryjQ/azdQ+M9Vf4=,iv:5Jsn/Y1hjMeDcFTa0bijxwq+60uIxWHW/vcdlz6AI38=,tag:7F2qgnyjTiPgzjspzGhK1Q==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
