#ENC[AES256_GCM,data:Wa/Lv2diKvM=,iv:uUSRSFKxq6DdkiZGwFu4+A/IHq8Eg+3eRuqrK/q1PWw=,tag:3JLITihQWeScUtIQQmG71w==,type:comment]
spotify_username: ENC[AES256_GCM,data:IBVnUscYAmplD5yU+V3AmO0Rqez4yrlO0w==,iv:4x2cvO5BJ0ls+1rTYPbcUQ25/QmaoVr5xauZHKJltfc=,tag:LPRnZeSjXIdVFlop/omyug==,type:str]
spotify_password: ENC[AES256_GCM,data:DEZMGAhy+Avitf0Jc4qN5j8=,iv:bBpl+0hVASMtpHSIyxl+KcrBpmodeT0qXPoYOCP/HnQ=,tag:7XsujdNy/n1ZFfjoZlgSxA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1x2t55uu60pkjsmggep284a4pvx05w7jyrxdnd503k26vp8ecnf2qk8zede
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTbEVQRGhqaEd0eUFLUHoy
            MHZxbHJVVkl1YUx0ZFMyaml5d0ZmOStoQTJvCkMwWkNZdFRYY29LZW8zazdsMzAz
            anZwR1FEMUlMRUg3QjNONTB1aTNEV0kKLS0tIGZYVDlhaXNNK083Rzl6OE5HbWxR
            MDlGZ0hOd3NrT0RGTzVyR0dxN1o2ZkUKf2thYYqqHvm9wEVY4UW+3K9xVOASS3kl
            FrpjqadOmwYDLdKMMCafMh1KrvVd3zs7lL/KjegUZUcw24IYUK2vTg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-30T21:07:48Z"
    mac: ENC[AES256_GCM,data:l0cKJhDgveGBMPD8dlCP7lJKGGpYZLVIRTf7NcK8JxxvE38O1HoG9nEwPEPU3P5WhnIK4JmLilBJxQmNV/jwp8r4UfI4EXu4J+/b6Nj2hThpxqvC4pLJbLrdfaQzmmUZzAXwgvhfAdAKwakgiTyOoXAtjPv1cJiydoWRd/LQWRg=,iv:phcNgM52afMQMfF6ufodRmKLUOhVECA3KuwqmoyWWMg=,tag:lzgzRi0daLr+zLY+80UGdg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
