cloudflare:
    api-token: ENC[AES256_GCM,data:ubpRUbeBpNpZbkI5M4I4teVGa018+DnSPyWnAcQ7v5y8hIZSHsEurQ==,iv:ztPxH3D8Srds2z+jsmzd5I8/PRTs8BdOTu9UEsAtTeE=,tag:BFd5eHtFj5YByCOLu4C2tA==,type:str]
    email: ENC[AES256_GCM,data:eTKd7FDlvniHeMTdd/8kCL5jtFW6C+/AyJcX,iv:4bMTrnkDXz6lKlCYjwxPgrYmMBB7lrhJxAfLPFMnB1o=,tag:tegiGGGDRvfkXUmkgOn+mg==,type:str]
misc:
    email: ENC[AES256_GCM,data:DGzYTNNnPEPG11HbLDCNQfTYq668PvbJqA==,iv:Sb3Az9f8vs89a+jlbHkoLY/MzJvVwRQ9+T6LfYq85tc=,tag:5imy2hPRD5V4e1wbSHEUdw==,type:str]
    gmail-app-password: ENC[AES256_GCM,data:cK8wqAdCxd2Ni/mqaXwmpzBxTw==,iv:OUbgqPPXU4MsVXRd65xVnCuElm7MkuGGznbRO0jIW4o=,tag:lQkA8GPGmWzYRBZsPBo1PQ==,type:str]
email:
    gmail: ENC[AES256_GCM,data:3j53nOmLwEBg+w8CVd8xjyV5UCM0N8Ijfg==,iv:IBa7Ww0cJxZedcsDmDpt0Hrju3PWTlST82pX3NzH6IM=,tag:M0yWVlttQ0ylIDTBNAcBqw==,type:str]
    outlook: ENC[AES256_GCM,data:RSzmQ4vxuE3WCQ1bht7N3UfRW/WwkvCob1wC,iv:SWyiq/tNH5ibh0unD+uP3FAYySdYlSoGm1gdNP3IbFg=,tag:QJ59PNkpjJPQR86JSBwcFw==,type:str]
    edu: ENC[AES256_GCM,data:C354TOSKMv3gH1P92sDqkHzL,iv:g+I3f9bQeRe7QsczLg2sLQVFb6ec5tCPP7oCiJWuR/k=,tag:WaN2I8MRS/WCBsq+9G4PBw==,type:str]
    realname: ENC[AES256_GCM,data:SOby6YETOATOhLfd5L3K7Q==,iv:6P7Uqdf1Rvo4NGDO+odmxfi0/tcru2U7yTxfDABGSiA=,tag:ura8gUWy9i5mLA1tbLcxug==,type:str]
sops:
    age:
        - recipient: age1laxes9xz25p0lhcflurv9mxyxm22g6ghw2d7c0hlxdkft7ettptsr7nmjw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByMWk1QmUwOE4xNDcwL0kw
            dXVZeGtXWjdzWTU2YjdJUVoxS0g5MlZ3a25JCmZYTFFVbG5UMTZWRGR3ZE1MQWho
            Z3FzQlozUXg2VFp2Ui9YMGVxbTRpb0kKLS0tIFFoeThKdXNCcnJhMnZjV0ozWWtB
            M01PMzNObHdhbTJUbjR0OWNPeGVEV28Km2CQ7u447CIKIXAJJhSLA6aiaMLmmOhV
            spgzpe7sLNr00W8ZZmEuPive1NcZOld4W2dpUgcD6b5Ny/nvbcEAPw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1g2ajxczmr86fua0a8qyj09laz4c4wl3yngx0rjces28seq8gk4mqthc4mp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNQ3NMelNpWG5jaXBaeWto
            SXZOZVdNZDhBQVl3dnl5YlN4U3B2cTUzclVvCjMyRDJaQUhqaFYzZVJFdUJ4WUdE
            SEtRWmtsWVd4bVpseGdKSHZuT3B6bkkKLS0tICtxVmFGNVYwMFBTNWtXL1RjMnpa
            ejhnVnRhSlZ1L1pPeG5GYnFsZG9rUDgKrkTy7KT3KOSvKaI2Ae5rSRIVkish0CgP
            OpLAHrJgNl7XJh2EST9+Plcq8jZYqK+QOScMyhQAtUFtd2LIYOrkpw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1vpwvdgz268pqt7m3xk0w6vu5z5j27quwn4p6xnghnyncqqn2m4ks9wlqg7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOMzUwWXErek5WRDdtYTBV
            dlBhdDY5WEVaN1ZYaHZhYWxhdWFRTUdOZXdVCnpUOW9sdU5NWWxFTFNSWHJYMDM0
            RHBBMmpHeXJJYXl6ekcwYmdLYUREamMKLS0tIFM5LzJ2T05KMHR0R3hsY1U5OVl2
            cE5iZlp6Ujh1cUZjQ1RWOEZWU0ZqMVUKQxSvanmzOo5qLO5QO6/McvAQfHyM6gmW
            hy6mGOmtZiFU4B2CUCKe9HcTQNUbDMHph/vKvCVUr9VCt5R23WFA3g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1lxmhrxyqjev4vznfsmve6fumlpqnudlyyur3wu6tymgj9gns7qlsnyv7wj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXNGVJOThTc0s4OXVrNWJ2
            Y3Y3dEsyemFjVHphaXJocms4RmxMUVVJUjBzCmxhT1JRbjI1cU5GWDNSdkhuZHBN
            a2F0ZU9OU054YlpUZ0VRQWRtalRDZEUKLS0tIElpWEZ2Uy8yMllhemYwQUR1YWxX
            d3BRaldXSVRXVFd1T0JiSzI3cDBPMU0KTRvlz86FXMHZVeTSaIn0Kg8w22CCsm5x
            NlYmRJtEs0o7yQgmHV46PKxvPbythAZGD2Laer7L9xBPmjZIStstDg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1knudcwfp6gjpwsgwks8ljcg836zvpgjukv5tzzqcnzwv8hsnlslq6990lj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtblNUMEJpb21aYnJ4eE9R
            VWkxUEN6THBMcmhibktybUFHT2FRZjVVL3drClJ0TVJIZzlSL0tzUG44bXYzSURz
            U01QOHV1TS9jZ1BFSWlqN2VsYnFBSHcKLS0tIDJwamprVGMwaGR0ZGhaNHhjSEda
            OTQyU1lHSzBpWDRkZERvTFZVSXNNR3MKLL9Y30Or8FDyDAMtJ1UabgDKY+LHnVhB
            8t/l8b6i8RDeLEISElm8eCDoQ/xHm2tHQwBr12KpdOvNaqPooATbVA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-09-13T13:19:51Z"
    mac: ENC[AES256_GCM,data:60VxnrVMRQIzPxabuXNkd3UEWqt2uWkMSB90+0ljsFSP0At2HihH8S62JfM9ExWtNvtxWlrdLt8rj6SJtNp3s9yw9p1adEs37SItzpWsQkL3pZlnjxmZ5ph9mzL7XDM4uJ9PF6YJt03oRo9IONkf+SAcHJbC6acK7T91NKohVPk=,iv:yF8p7oFwfqbj5V1PtaNKTnmIAetYDsA8qOTUOP3X8PQ=,tag:eWMSxt5AaHBHiWgTiWawgw==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.10.2
