example: ENC[AES256_GCM,data:uCGyseGgCsZGdl+EMgxorqPrzgVSwPuu1Sv+sWFAIaYP+iAEbI0S/obhBlv8gg==,iv:O8+wRff+06RQWKmOALFU8Lt5EDT03ymALlTjxm83OOs=,tag:dROSOTqvOsbn9/AtTQ3N2Q==,type:str]
example_key: ENC[AES256_GCM,data:KHEZSCCMS1zDgchtYg==,iv:46D3wWDTwV2bYBhMVX+fiCRrvrPOsSs/V1df8pZua1k=,tag:iDoAfk5TIwTJTJMj4lq2Yg==,type:str]
#ENC[AES256_GCM,data:bM4Ri1lzcWGYuRlL6sdocQ==,iv:iMAhc8rb0BW990Ni38zug586iGDtMCfDG3C+LYbOv7w=,tag:fIwi9XvwnquEk1TdEF0fFg==,type:comment]
example_array:
    - ENC[AES256_GCM,data:2WYH/98lPZnOx9auoEs=,iv:GnwtZiLQoKogtYp1Lxb70RHWh8nvrZAWsqQUpNbup3I=,tag:1pEj+K0Zx1UhIaNC0uZMeA==,type:str]
    - ENC[AES256_GCM,data:Mlqbgc3KsCYTZGtTtzw=,iv:abQStMrC56fyTx2n+xOdpefUISXxdnafzrjQVf2XFHM=,tag:UShtHGB+Enrot6XY/EFB/A==,type:str]
example_number: ENC[AES256_GCM,data:83Rb2aeS1Y06Ig==,iv:58sHDB1NjXPtZoArlQQ4rRu///HamWyBCykafEGXBK0=,tag:mXDqykEurpTQ+39OluDD3A==,type:float]
example_booleans:
    - ENC[AES256_GCM,data:0ZBCdg==,iv:3YWs1GjbG/CwrIt/rU+QeS8AHW4xm1YGmON4ApvAi+0=,tag:ZnprhIAMTwAJ+mIF+VM9oA==,type:bool]
    - ENC[AES256_GCM,data:CqtOrKI=,iv:UDwarg0EGvD5ReHiNDRyVV6qgVjHx1SLnXRR6LYNfhI=,tag:cnuRa0EQ7BQxHbmW2p3GfQ==,type:bool]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1laxes9xz25p0lhcflurv9mxyxm22g6ghw2d7c0hlxdkft7ettptsr7nmjw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsUndsRktFTGhOaW4vb3hk
            VmNEM0VwYlR5QnEyN2k0VkE5NTQyN1hsbWpVCnA2djRDKzdSNnFNVVlnQ2JUby9W
            eSt2TWl5eGdyYWpKbHZ0UWNIN3BWMUUKLS0tIERTNytTOURwWWcwV2RNSVIzUXdu
            MHpDZThFNDc5TXY2akdINFZ6cDJIOWMKXWv/opBzzbtXuZW+plDPWRsgf4K9JHVS
            q5ttTaLquWczr1IS55R/ZXPqjt1xAz5B7AG2NobU2SwMdOwOn5FzHg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1g2ajxczmr86fua0a8qyj09laz4c4wl3yngx0rjces28seq8gk4mqthc4mp
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlR2thUEJZblNDTy9TajNN
            MkQvYXpmdmhoVHVLT1lQVllHOEtqVTlSbnlrCnN4d1Y4VkMreURGL28yK2dHWWNV
            d082TlZpbFNQT29xeFExQ0JsVEVCK2cKLS0tIHpuUk15ajlseUttaXY3TlpHT2pX
            V0kwbE9LWGxiRllqV1Uyd1REZE50eHMK7le5JKMup66lnla6fRxVZP3kpeIj9zAP
            u6qxETXImSRMWi7djJIQnwiUdvHi6Z+j68P7Gi9/QsUIXguB0Ir9MA==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1vpwvdgz268pqt7m3xk0w6vu5z5j27quwn4p6xnghnyncqqn2m4ks9wlqg7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkVWkvalZxcVBwN2RpTGpD
            L2N0amlyQktzaXBweG5YMFZMMmE5L0NzWVJNCmJBeG80SFBRbm9ETGZ2NUJmUG9w
            NG9kL0pOaHNmSzdBNWVGSXpoeHl1MG8KLS0tIFc1Nmc4V0hCQVdUQm1JOElwT2FG
            NE1KT0NZNjY5K0xIUG9FcGZsU0orMkkKzBF30NpeynqQn4nHLrOaWcdwjCNuVcYC
            kd5htbQn+qngOvM+uO0COecNeX7x4nt1C1BAco1PAKI9tJMHTfdO8g==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1lxmhrxyqjev4vznfsmve6fumlpqnudlyyur3wu6tymgj9gns7qlsnyv7wj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNTVo3bzdjQTI0S2Z0R2pw
            SitJQWRBOS9IWEFmanRmZTRzM2QydWJsU2xNCkZCTmQ1Rm1jNHRGOGJLeUFFek01
            RzRzaTNaMVpraThoTUZXcG44RHNqZjgKLS0tIGxtMW5CU2dlZjF5bE54dG9sQks5
            U0J3MWlVamR5Tk9uOSszNDJ4R241bmsKcx8wHHtI6YR8i8EAZ661ao44UdI9qiH7
            +66/6fnfmYj5GyM5gD0sRkEesscFIUAg+SOQPGcofTdiHt1FEBLvJQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-07-31T05:52:47Z"
    mac: ENC[AES256_GCM,data:cTgzFYvnrQ97hBIcpUsVTqGPP43Rvy7hFDRm+SYBqkZRjlF78DuY4K86+MLMQv3Ec9QdG4m0WDFyAARw6jg0dEhBWufHHGZ7g9mT8NuyaD2asuKAeBJARW/0uUwbTVAQ6WE8NAVv23mb4Mv2KSXlG9xT84wy9r2GYR2eydpftc4=,iv:iGRkGVPdG0jF07Y0YdclE4L697RFS8VIQ4BG8+XXHHI=,tag:3WevZhRjV5/UTKaufclD0g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.0
