github:
    user-email: ENC[AES256_GCM,data:28KM8QCyy017xzpZ+3SQcsinkXQmXT9JoSAbLZJBvfOXOkeoErBf/lnOjrWJbXI=,iv:5mc0OO43HNRInZjYS7dqTmC14KjRoEtAUQ/NMxZ55Cw=,tag:hglUKP7V1xP7RSTMxW3WHA==,type:str]
    user-name: ENC[AES256_GCM,data:zg==,iv:HPHQuoMj7R0iamSLDghQ4rpzCtYG6YKmvNHkt4d9vfU=,tag:glsQLlUc1t6RAlEO9InMRQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1laxes9xz25p0lhcflurv9mxyxm22g6ghw2d7c0hlxdkft7ettptsr7nmjw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWRk10T1l5SEVsbEJJdGZa
            T090QmR4NHB5Q1Q2UjUrUHRsYXVzUWpQeUdJCmNhT0xIZTlBNnd0QklHYkJuUmEy
            cVpxL003MUxXQ0NsMllsUHhkVFljcjgKLS0tIGdtN3VJOG1aTkRsdkZNbGdxTGV3
            UnhLaEh2c0lJazZZUnk3VlZQVUVoNEkK7C23mVa8mDNanJbcVEoH3g74wU6j78Dr
            92rn+IqlotpQGPGaVP3DIOSwYB7CwZUQH4pa4p6PsBZkFzs/FAe+vw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1vpwvdgz268pqt7m3xk0w6vu5z5j27quwn4p6xnghnyncqqn2m4ks9wlqg7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsL3pyL2Q4OWpQQitVZE9F
            cjJ1bC9seTNzRSt1bjZHdE15Rm1oOGhoQkhjCjhyMkVaWnZyUHFONW1pdUJWQmhm
            cU9QdkFnQnAvRVZKSmdDcEg4ZXFCRE0KLS0tIEViSWhmYlZmQjkrWWt5bzNMc1lv
            SFVrdGsrYWpNaUJPYjlYS01PY09GQjgKXhHAlYggRHv/aGqi63i9VoNDLtEQzGTB
            XXXAGfUKjbKBXCQyCoqyrZy9UUBGFa1KYO8w0NRUvDKt0HaiU1tV3A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1lxmhrxyqjev4vznfsmve6fumlpqnudlyyur3wu6tymgj9gns7qlsnyv7wj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnQ2FsS3dOOFp2c0RWRitY
            MzNLd2JVNWVPenVlaVFZcFNyYWtUVURIRTBzCkZwVmVrQ1FhY2d6aTRCcSs5aVhD
            aCtmNUYrRVBidzE0bWtMVFUwNC95bTAKLS0tIFI3eFNZQ3dGTHkwY2NZaTluOE5u
            U3YzVnhyZit2ZFBYSmJrNy9BYkRkbncKfDrbYG1kcER1PnJGkZwxtYjbUiKSlPBj
            uFQPQcDn5Hoh6nGx/uwc1InmoqZipaeeNI/2iGBLGCqha+ZnANZohw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-02-28T19:41:58Z"
    mac: ENC[AES256_GCM,data:1Edx5a0VuwdKNKghN99Rv/HE+vOeLOWUX9bbf3WGx3dP6ASg6ek4wPftVFyio+C0g1a6XTimTXcyrsPYY8M4rkPOl/Ot6tMSATfqU7rYoSsmiQJrUr3SeqWRit6gOnUVH/UJESZ3gAsRSvJ2hMnbIKg5cn0xdECVP7sOHoRV/OM=,iv:braD68CVCwGs/HLiaHF9Xu8p4XVyloR4m/ltf4q3e6s=,tag:MDGgakcAR4VIzts+cpBLPw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
