spotify_password: ENC[AES256_GCM,data:F60c7i0TnGL6pJ0lF5v5ObA=,iv:rqbpX6JkVrQb1ZwCHEIWYsjCDf43oMPYZgw4kmVE7Tk=,tag:nOUxS3wtYBdbVT+lSHI4zA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1x2t55uu60pkjsmggep284a4pvx05w7jyrxdnd503k26vp8ecnf2qk8zede
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiMTBhNjBpZVhON2JkZVQx
            ZTBNbC9UdmdOY3dTOGRrblQ4Z2pmUUpKRVQ0CmV2U1loT3BBeEFWRmVQV0JuNnds
            dlRnRUVwVVF3RGJ6UDg5VDBkTkIyTVkKLS0tIFczeHRJQW14TFd1UC9vWEhkalZj
            QUV5eUExeWQrb0JaNUFBaUlLNU93RVkK2hF5QSy5FkxFByBoagTjED8Fv+hQi9mu
            OKZk2CsBQ1jzwgmJgOM4krr/g9cJV64yBALoD41/o3SCIhtO5sDhBg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1xqfk33phztpmuxefzmgm9rhew320hj5rd0389hcf682z7nfvhs2shdrwxj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxcnpXYjNLVEszVlFJSllH
            b1h2NlhDN1BKY2JFSFZEWkw4ZzdBMFVEQTE0ClpTc2VYUVpTUGRkNDFQTitVTjNM
            bVFKdXFYUDFqakVrV3E2THlxUXBXVHcKLS0tIExubFZ2SVB6aUdXTml4ZmxxY0sy
            U3RRMTZuVENBZHhxYjkrV1lmcll2RGsKjUguUmXibgRDuscK1/uS/TAEDWlb3uY6
            5StAmEtL/K7jOn7Jn2f6LKeqSwjZ59ePblTLXP3N+6q5KoitQQLldw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-07-31T14:15:44Z"
    mac: ENC[AES256_GCM,data:5CW09L4EI05UmsvvZR14cgbwY4qDFF+aUJUqdmrzJoH6vZZbGaFhEiqOI3XUrdfX+cZ+4mgQK93kZa6rC67QFOpMez7XEqz1qlhdlFjN/5c3zyDsQTPPX9yevnKPkmQ6tte82lMh8buNL/e+DT99puUF8zbH1lFeXDhbdB4J48M=,iv:qvXHwNK5sO54wTHbhHn1+61T1pv5XdKVK1zJbxykPLw=,tag:PNZA0Om3q9iue6uRbES9CQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
