#ENC[AES256_GCM,data:3W6KWptevgwvzo6wLZEh5AZTrrs=,iv:2LYHy2vEnr0YcfGRIk0huG9KWNGKqiJNCJqVw2K+ReA=,tag:8ucxhQQg3lX8/BlWxSc+oQ==,type:comment]
users_alex_password: ENC[AES256_GCM,data:eRrjFnUX,iv:x0ii93Q9ULpodBnk5ETUFeaK8kJE73zoreUuYjniCOY=,tag:pz3pRZV6ub8cnNSkULqEQw==,type:int]
users_oli_password: ENC[AES256_GCM,data:qEXH,iv:QO3QADQ1wQpt/bUf4SijAulpQTBRJq9iFZPSNE/8pks=,tag:zyPit/8MVbJ+9pH7MEq6HQ==,type:int]
#ENC[AES256_GCM,data:96g/2qUMjQUmSwr5Zu+iqBMZOA==,iv://yCDao8kFyN7zGueip8vUE06W8hN6An8WaL0kJSzs4=,tag:hAoNYfohUS7RMY46Cw6f0w==,type:comment]
spotify_password: ENC[AES256_GCM,data:F60c7i0TnGL6pJ0lF5v5ObA=,iv:rqbpX6JkVrQb1ZwCHEIWYsjCDf43oMPYZgw4kmVE7Tk=,tag:nOUxS3wtYBdbVT+lSHI4zA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1x2t55uu60pkjsmggep284a4pvx05w7jyrxdnd503k26vp8ecnf2qk8zede
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiMTBhNjBpZVhON2JkZVQx
            ZTBNbC9UdmdOY3dTOGRrblQ4Z2pmUUpKRVQ0CmV2U1loT3BBeEFWRmVQV0JuNnds
            dlRnRUVwVVF3RGJ6UDg5VDBkTkIyTVkKLS0tIFczeHRJQW14TFd1UC9vWEhkalZj
            QUV5eUExeWQrb0JaNUFBaUlLNU93RVkK2hF5QSy5FkxFByBoagTjED8Fv+hQi9mu
            OKZk2CsBQ1jzwgmJgOM4krr/g9cJV64yBALoD41/o3SCIhtO5sDhBg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1xqfk33phztpmuxefzmgm9rhew320hj5rd0389hcf682z7nfvhs2shdrwxj
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxcnpXYjNLVEszVlFJSllH
            b1h2NlhDN1BKY2JFSFZEWkw4ZzdBMFVEQTE0ClpTc2VYUVpTUGRkNDFQTitVTjNM
            bVFKdXFYUDFqakVrV3E2THlxUXBXVHcKLS0tIExubFZ2SVB6aUdXTml4ZmxxY0sy
            U3RRMTZuVENBZHhxYjkrV1lmcll2RGsKjUguUmXibgRDuscK1/uS/TAEDWlb3uY6
            5StAmEtL/K7jOn7Jn2f6LKeqSwjZ59ePblTLXP3N+6q5KoitQQLldw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-09-10T15:36:32Z"
    mac: ENC[AES256_GCM,data:5lqBkHbj99+pcK3fL+7Hcc4Py/QJBwQRMUW+0g4Jiejm+YWhqtBUNm8YQF2aH0PavZzHCZur4fRQq+RoKhnNlRxj6wPLqL0awBXXF6h5nhje/s2b3J/4y5L+8X6FQKJFjSdhEHx6FcSjn/dZxYXL8cQicsTJ4itLwtKhINFE6Oc=,iv:DmP+eEYH+kg0RzmR5089vFwXN2CujGpuA552q6rtAjg=,tag:MofmGRoTrn5/+md+cmGAMg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
