#ENC[AES256_GCM,data:nBlMHuFYyg==,iv:pfSU/oaqEeWh1M71TyDX5ms8ZQKDJpK62CC/WOi5AP4=,tag:Nt3iss2TCniI3ijXhiwWfA==,type:comment]
defaultPassword: ENC[AES256_GCM,data:0g+zVcPO,iv:ogGnExBiQ8k6qWvFoaRuDc8fHl9eagxEkiCGy+gBBoo=,tag:sSXiIcfNX1clfyy5XlBcww==,type:int]
#ENC[AES256_GCM,data:PC8gGG6U5Fyt,iv:+k0lYtbXRMO5pzDodHQ8bpx2B6gqsqnrgpOfrggk9AU=,tag:gxlut2uH4LWoCss1J7lhJQ==,type:comment]
spotifyPassword: ENC[AES256_GCM,data:RmfIcdZllqa9/QenYPdSUqw=,iv:qHqpIt7Wd6RnoNlHC7uuF4d2v5vPOHyTylKdeEfY3q0=,tag:O/NJQnAH41/n4OFyGQr9/w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1x2t55uu60pkjsmggep284a4pvx05w7jyrxdnd503k26vp8ecnf2qk8zede
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5SzU4UWd1OEJtZC9QdDlj
            Slg0QjBBc3IwMTVCdDhpTk9Ib2l2WEpmb0NFCnM0YTZlQTY2YWc3WFdQWVhSNWhO
            ajNVSm5XMVEwWTF3NTd6SUFGVkw2NU0KLS0tIFNjUXQvMnBleGNNWklBOEtSZk1U
            MlF0djk1WlRkTUpjVUhlTVFNQXh5eTQKd20GqffX1FnKilf6/fL86rG4e1UcEHLN
            LgD4cdlh9zaGinNuc9vH03zUBHKAFTIRJMPZM7cGwPYrBesTzir+wg==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1vpwvdgz268pqt7m3xk0w6vu5z5j27quwn4p6xnghnyncqqn2m4ks9wlqg7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjYUJCMzg2NXpIcGlEMFJU
            aDhGUE5uQXR4a1V5UEcvcWZudmltQnVSeDNnCmo5RWhsTUFWa215c3J4Mnl2dWM2
            cXFEenRNcXBaRUdQSVl1WHhpdXNMUDgKLS0tIFExL1VkczhCMDNsbDljMWFMckJz
            Wjg3Q3l6T2tQQ2JUSmFPb1pMaTV0cVkK6mOshb3M345gpbZwwsdnxyeEhJiJX+WJ
            qbjbR88HhQyai5TLLL/QWnhkOKkpsdW3plnITIrvFeRPclCEKhQaaA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-17T01:59:23Z"
    mac: ENC[AES256_GCM,data:6O4Uuq550P1HtHHdDzVbHRmq3fS7J5oaMNW6tSBHc4p+6ERMA36ahZqrjrvroxiq3Mscqxx8W2oo0MzWMLaxrTyXCT2Hz8cUyaj9GUYn5yOZO7aScGtZ804ZmgKgB87m2CRkWDDtIL7Ld2RF2V5XuU2WAJqM9tDNH68CGwjUx+c=,iv:+OKN+hi0IWkeJeY9gfXX//KibJWpupvIHMCVTRt4N2s=,tag:SdgAFZ4gJV/u0FwbFRgFyg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
